{% set version = "1.0.19" %}

package:
  name: ipaddress
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipaddress/ipaddress-{{ version }}.tar.gz
  sha256: 200d8686011d470b5e4de207d803445deee427455cd0cb7c982b68cf82524f81

build:
  number: 0
  noarch: python
  skip: true  # [py>=33]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.3
    - pip
  run:
    - python >=3.3

test:
  imports:
    - ipaddress

about:
  home: https://github.com/phihag/ipaddress
  license: PSF 2
  license_file: LICENSE
  summary: 'IPv4/IPv6 manipulation library'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
