{% set name = "ipaddress" %}
{% set version = "1.0.18" %}
{% set sha256 = "5d8534c8e185f2d8a1fda1ef73f2c8f4b23264e8e30063feeb9511d492a413e1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py>=33]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - ipaddress

about:
  home: https://github.com/phihag/ipaddress
  license: PSF 2
  license_file: LICENSE
  license_family: PSF
  summary: 'IPv4/IPv6 manipulation library'
  description: |
    Python 3.3's ipadress for older Python versions
  doc_url: https://pypi.python.org/pypi/ipaddress
  dev_url: https://github.com/phihag/ipaddress
  doc_source_url: https://github.com/phihag/ipaddress/blob/master/README.md

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
