travis:
  secure:
    BINSTAR_TOKEN: AlQ4Se1ReRv37bAjZailtoxBi+3K4/pfPvlUGSR1XpDpOuRz91XXCAWJVxieltEXtISZnabPL2O+hYxBcpil0/tdPXg5RKPdkvsuJQc1Yv8K43aTh1X6Hg1f/MZhpcc7vA1vMuTOAarzAa9LVpBdB1+/+W9nroYi6gp0kMt10PMuLuqnhw9u6GtzF5rMDQeUHoFzY2yzfoe4r1BYLJJM0jO+FVL07FzEpX90Bvw3CO1yXEX9GvfIptSMEKYJhqUa2y3n/Phq/tpdVBSkFQLKqz3gj9bXfjcclZQiLv6QuoQAXhVb44YAyIIx+HCp8udeFcsttt59zanL+u3vSKJ69hncznzAYHGXzkF95eaHr9txAcV4r10U1psAj8NP3F4AvpKaN70PtN3ix6MGJ/ztkpxEVJXLecoyT/dgA17DWe0mM3/nhTWPfEU76xVnYcV1ij8u9nHfZnZGwhbgaJdDnbC7/iRR5VtCbVy051GAYa34H50xmBiEkBbNyr9htOET2TlfoZLWA6dqdhMM89wYHKeyVowtZJ30zu6WqBPjQ/+cijSpigazFx1Sri3pR8G1PKK1Z68a/YnLjsDsKvkLNg/NQNlua1SsZvm8lbnLcs9HQBMBGzPyTmYmJjVUYwVuGPw/C1GvmhsRkH1d39ky6UV+QZzJSKVCl0ZY5RAVmlE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
