travis:
  secure:
    BINSTAR_TOKEN: Yl+gwyCnT1t0AYPlL9S0nvM3xizpRypuIiMbPV0AcSOKDbwNRQ0AzdfkYfCxLA9O1quORo6bNCtrcxjImCitBrPsx+/jUuwRuqfhhPFmxzcm7NLRrsqO9HNQeLN/x3plVez4OIdZY3EGUuWr0pB6QyAda5FMp293/cAvk1wDoZglYQrGNJ5OzQEUP8Jt/dcKTRwAAoJMl2ZlKJ5t1eBcxkXAOoHNYGXHeHaR5Dyjw6InRSSF2KElyakFMleLa9H8+0A0Th/pbZcIHD00DY2m/IM4aIVck4QHqLyKNMJVYynlSH77h0JUglOEL/Wfv0duRQTWO5BgK6K1ZBvRdQ6Q434mapt0gqiGMGtehbHK+Bj90vsHuo7cWsPvoUngLwrd39l8CL3GkJYg/Andgh1CSyGCta4htq7koOemQGnXvmAeBs8Uh57bVNCm75RypU4iCWaG3jX//IPbzrsskYiELxPxtcNfGbTmfcxoxDQs2ZySFpsyEJ0kjGtubbECzz5usnG2xZu2vUKMLgky+nA3kT9yyjWZP4rvB4GmHpTvzkMlmp54GvfNC8kazu5LvcTvmE2SoMjbF9mB5ID2h1AYL8Xekg9hX9FBfpzgd1vwuBwLJnhBVNqYW239bVlvKKKHDt+43ZCLeZ+28dDldl3L+LxZy6EgSSQgJZFkywLhYaY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
